### ISSUE TITLE
Panic while compiling some regex during a find the secrets run

### ISSUE THREAD

**Issue by CSBaum** [edoardottt/cariddi#1]
**Describe the bug**
Panic while compiling some regex during a find the secrets (-s) run.  It also happens with the `-e` flag as well.

```
panic: regexp: Compile(`*`): error parsing regexp: missing argument to repetition operator: `*`

goroutine 1 [running]:
regexp.MustCompile(0x14fb20a, 0x1, 0x0)
	/usr/local/Cellar/go/1.16.4/libexec/src/regexp/regexp.go:311 +0x157
github.com/edoardottt/cariddi/crawler.Crawler(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x14, 0x1, 0x0, ...)
	/Users/sean/repos/cariddi/crawler/colly.go:54 +0x1ce
main.main()
	/Users/sean/repos/cariddi/main.go:91 +0x3cf
```

**To Reproduce**

1. Create urls file with a valid url in it
2. Run the following command: cat urls|./cariddi -d 2 -s
3. See stack trace shortly after launching

**Expected behavior**
Cariddi should process the provided site and find any/all secrets

**Desktop (please complete the following information):**
 - OS:  Mac OS 
 - Version: 11.4 (Bug Sur)

**Comment by CSBaum** [comment]
If i can carve out some time later today/this week, I will try to take a look at the underlying code and see if I can help out with the fix.

**Comment by edoardottt** [comment]
Hi @CSBaum ! 
First of all really thank you for your help! 
I think the error was that there was a blank line in the input file and then the crawler had a bad behaviour with the url regex.
I added [this check](https://github.com/edoardottt/cariddi/blob/main/input/input.go#L43) to fix the error, let me know if now you can crawl properly and everything works fine.

Thank you another time and let me know. If you get other problems, don't hesitate to open new issues :)

**Comment by CSBaum** [comment]
It was indeed a blank line in my urls file, but the fix on line 43 doesn't seem to resolve the issue on my end. I ended up removing the blank line from the urls file and things did work correctly.  Could you switch to `Scanln()` so it would ignore the last newline / EOF?

**Comment by edoardottt** [comment]
It seems I have to change a lot the code with fmt.Scanln and also I would like to take a full line as input.
What about [this](https://github.com/edoardottt/cariddi/blob/main/input/input.go#L43) ?

Thank you another time :)

**Comment by CSBaum** [comment]
That did the trick!  I re-added the blank line in the url text file and used the latest code from the repo and the call completed successfully :)

Thanks again for the quick fix!
