### ISSUE TITLE
Refactor visitHTMLLink()

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/cariddi#100]
Context: https://github.com/edoardottt/cariddi/discussions/94#discussioncomment-4162573

**Comment by edoardottt** [comment]
Maybe I'm not understanding what you mean...This is the implementation of `Request.Visit`:
```Go
// Visit continues Collector's collecting job by creating a
// request and preserves the Context of the previous request.
// Visit also calls the previously provided callbacks
func (r *Request) Visit(URL string) error {
	return r.collector.scrape(r.AbsoluteURL(URL), "GET", r.Depth+1, nil, r.Ctx, nil, true)
}
```

**Comment by cyb3rjerry** [comment]
Yes but it uses the context that's defined at the collector's creation (URLs to ignore for example)

All of the "ignoring checks" that are manually there here:
https://github.com/edoardottt/cariddi/blob/4d590282a85f9fd2f64f279018e7dbc03c520711/pkg/crawler/colly.go#L381-L383
Are already taken into account via the context if you use `e.Request.Visit(e...)`

**Comment by edoardottt** [comment]
aaah okok now I got it ahaha (I thought you was referring to this with the word 'context': https://github.com/gocolly/colly/blob/947eeead97b39d46ce2c89b06164c78b39d25759/response.go#L36).
Anyway, yes I know. I have tried in initial releases to implement the current behavior using that struct, but without success. I have encountered difficulties with -intensive mode, ignoring URLs... but of course if you want to use them it's super okay. I mean, they are built for these types of usage :)

**Comment by edoardottt** [comment]
Actually the implementation of -intensive, ignoring URLs etc.. should be done in CreateColly passing the Scan struct and playing with the fields and methods of the collector object. 
We should also have clear test cases to test URLs ignoring and intensive mode

**Comment by cyb3rjerry** [comment]
Souldn't be too crazy to do via `[DisallowedURLFilters](https://github.com/gocolly/colly/blob/v1.2.0/colly.go#L54)` which can take a Regex
