### ISSUE TITLE
Add JSON functionality and console reporting of secrets, errors

### ISSUE THREAD

**Issue by ocervell** [edoardottt/cariddi#103]
Would be great if the tool could take a `-json` option to output JSON like similar tools (katana, gospider, gau).

It could output JSON Lines that way and have a 'type' key for secrets and regex matches etc... instead of putting everything in a folder.

Example output:

```
{"source":"href","type":"url","output":"https://example.com/path/","status":403,"length":140}
{"source":"body","type":"url","output":"https://example.com/path2/","status":403,"length":140}
{"source":"https://example.com/path3.js?v=1652869476","type":"secretfinder","output":"<AWS_SECRET_KEY>","status":0,"length":0}
```

Thoughts ?

**Comment by edoardottt** [comment]
Hi @ocervell! Thanks to be interested in the project.  
Of course I can add JSON output to cariddi, it's not rocket science and I think too it can be useful.

Unfortunately now I'm really busy with my thesis, work and other projects so I don't know when I will be able to push this new feature. Anyway thanks to point out this thing.

Have a nice day

**Comment by Tezas-6174** [comment]
Is this issue still open? If yes, I'd like to work on it.

**Comment by edoardottt** [comment]
yes @Tezas-6174 it's open :)

I suggest to continue the work started in https://github.com/edoardottt/cariddi/pull/106. Maybe it would be better to add the flag `-oj` instead of `-json` just to be consistent with previous output methods:
```
-oh string
    	Write the output into an HTML file.
-ot string
    	Write the output into a TXT file.
```

the flag should take as input a string and output results like oh and ot do (separate files for results, secret etc. etc.)

Ask me for any doubt

**Comment by Tezas-6174** [comment]
Alright, I'll start working on it and let you know if I get stuck somewhere.

**Comment by Tezas-6174** [comment]
I had a doubt,
 
![image](https://user-images.githubusercontent.com/75741089/226189231-a58f2ded-dce8-47e9-9da8-53544d2d1ab8.png)

- Here, in the `New()` function, the function `visitHTMLLink()` was not called correctly as 11 arguments are passed, although it takes only four arguments: the link, event, HTML element, and the collector. I changed it to 4 arguments, but I need to figure out what the event is.
- If I get this, then the link will be visited, and the HTML and XML events will be registered.
- Also, I have changed the option from `-json` to `-oj`.

**Comment by edoardottt** [comment]
have you forked the main or the dev branch? I think the dev is some commits forward, you should use that branch for new features

**Comment by Tezas-6174** [comment]
No, actually, the `devel` branch is three commits behind the main. I cloned this repo and pulled the changes in the unmerged pull request #106.

**Comment by edoardottt** [comment]
ok got it, the problem there is that that development branch has conflicts that must be resolved. mybe it's better if you clone the dev branch and apply the changes on your own

**Comment by ocervell** [comment]
Sorry for the delay on this PR, didn't have much time on my hand and the linter wouldn't work locally... I can take over it if you want, the conflicts with main shouldn't be very hard to fix.

**Comment by edoardottt** [comment]
Sorry Olivier but time passed and Tezas wanted to work on this, you can try to fix the conflicts and realign the changes made with the requests in the previous messages. However, in my opinion is better to avoid "competition" on the same issue and try to distribute the workload on more devs :)  
There is a lot of work to be done in this repo and I suggest to choose another issue or create new ones. I will be very happy to help you contributing here

**Comment by ocervell** [comment]
Sure, no worries.

@Tezas-6174 please note that altough `-oJ` might be a good option for real JSON file output, imo it should be distinguished from JSON lines, such as:

`cariddi -oJ output.json` would write a formatted JSON file, but `cariddi -json` could output JSON lines (in real-time) so that it's consumeable in real time by e.g `jq`, in a similar behavior as for example `httpx` or `subfinder` tools. 

Both options are not mutually exclusive either, and we should be able to write `cariddi -oJ output.json -json` which would emit JSON lines on the console **and** save the output to a file at the end of the run.

**Comment by edoardottt** [comment]
you know? you're right. However, there are some constraints/problems with this implementation. 

1. cariddi can't output json lines as you designed them (including secrets and other stuff) in real-time because it parses all the stuff at the end of the crawling (only URLs are printed in real-time since it's impossible to have duplicates).
2. It would be better to have a single implementation of json output, then I agree it can be used both for `-oj` and `-json` options.

Regarding point 1, maybe it's possible but there could be duplicates in the results.

cc @Tezas-6174

**Comment by ocervell** [comment]
I respectfully disagree ;)

For 1. correct me if I'm wrong but we actually hunt errors, secrets and infos in the `c.OnResponse` function so it is accessible on a per-response basis and thus outputable (is this even a valid word ?) in real-time ! This branch [branch](https://github.com/ocervell/cariddi/tree/merge-dev) has the implementation (and is up-to-date with `devel` in case @Tezas-6174 wants to pull from it).

For 2., imo JSON and JSON lines are two different output formats. That said, you _could_ implement both with the same flag, such as when not passing anything to the -oJ flag it would output JSON lines, and when passing a file path it would save results in actual files instead.

I find JSON lines to be a great feature since being able to parse results in real-time to do further actions (pass to other tools like `gf`, `jq`, or save results to a NoSQL db) is a time-saver for sure. If you look at similar tools (`ffuf`, `gobuster`, `katana`), they all have a way to output real-time.

**Comment by ocervell** [comment]
I forgot to mention the eventual duplicates we could get: I didn't see any in the tests I ran, but if they were, maybe we could keep a cache of URLs visited and prevent re-crawling them (that's actually probably another feature).

**Comment by edoardottt** [comment]
My fault, you are correct for both points ahahaha. 

1. I was mistaken with "final" output, e.g. if I find the same API key in two different URLs I just want to output once. Anyway using `-json` it's correct to print it whenever I see that.
2. I was thinking to the JSON creation, not the actual structs. But carefully thinking about that, it's so little code that it doesn't care. Or maybe I don't even have a clear high-level view of the implementation.

@ocervell u can start working on that, if u have any issue ping me and I'll be very happy to discuss changes or anything
