### ISSUE TITLE
Example Regex File

### ISSUE THREAD

**Issue by jaikishantulswani** [edoardottt/cariddi#118]
@edoardottt provide an example format for custom regex file.

**Comment by jaikishantulswani** [comment]
@edoardottt It would be much more easy if we use this only for scanning secrets like an argument to `-only-scan` 

echo "https://example.com" | cariddi -only-scan

**Comment by edoardottt** [comment]
I'm not sure what you are trying to suggest... Can u be more specific?

**Comment by jaikishantulswani** [comment]
@edoardottt like we already have a file containing links crawled from other tool and now we use caridddi to only scan for secrets 

echo "https://example.com/x.js" | cariddi -only-scan

cat "links.txt" | cariddi -onlyscan

**Comment by edoardottt** [comment]
ok... so cariddi not following/crawling anymore links found on the target but only scanning for things in the content. right? If yes, can you open a new issue with detailed description and examples? This will be developed for next releases :)

Thanks for the suggestion, appreciated!🎉

**Comment by jaikishantulswani** [comment]
and also @edoardottt If I create a regex file like the below it is not working

```
(?i)([a-zA-Z0-9_.+-]+@[a-zA-Z0-9]+[a-zA-Z0-9-]*\.[a-zA-Z0-9-.]*[a-zA-Z0-9]{2,})
(?i)([\"']?api[_-]?key[\"']?[^\\S\r\n]*[=:][^\\S\r\n]*[\"']?[\\w-]+[\"'])
```

**Comment by edoardottt** [comment]
what do you mean is not working? Regexes must be valid Golang regexes to be used, if I try to look for multiple regexes they are working fine. Do u mean the tool is panicking, not finding something that you're sure it should be found or what else?

**Comment by jaikishantulswani** [comment]
I am testing this on a local hosted file in which these should be found with name 'key'

**Comment by edoardottt** [comment]
ok, try to test also the regex matching the secret on https://regex101.com/ or similar tools. Just to be sure the regex is okay (remember to select golang regex). Or if you want share the file on pastebin, so I can test it too.

**Comment by edoardottt** [comment]
@jaikishantulswani have you tried using that website? Do you still have issues?
