### ISSUE TITLE
Scan Only

### ISSUE THREAD

**Issue by jaikishantulswani** [edoardottt/cariddi#119]
@edoardottt Would be helpful if cariddi have a feature to only scan endpoints (not crawl) like with an argument `-only-scan`

```
echo "https://example.com/x.js" | cariddi -only-scan
cat "links.txt" | cariddi -onlyscan
```

**Comment by edoardottt** [comment]
Thanks @jaikishantulswani :)

**Comment by ocervell** [comment]
+1 btw ! Differenciating `crawling` and `hunting` modes basically. 

On top of this, I'm wondering if the `hunting` mode shouldn't also allow offline response parsing...

For instance, you capture responses with Burp or other tools (`httpx`, `katana`, `gau`, `gospider`) and you can analyze those responses files (txt?) with cariddi's embedded patterns.

**Comment by edoardottt** [comment]
@ocervell I agree, this would be reimplementing [gf](https://github.com/tomnomnom/gf/).

**Comment by ocervell** [comment]
Maybe we might need an issue to allow saving raw HTTP requests & responses.

**Comment by edoardottt** [comment]
Agree https://github.com/edoardottt/cariddi/issues/121 @ocervell

**Comment by edoardottt** [comment]
> Maybe we might need an issue to allow saving raw HTTP requests & responses.

https://github.com/edoardottt/cariddi/issues/121
