### ISSUE TITLE
Store raw HTTP responses

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/cariddi#121]
Add `-sr` to store the HTTP responses (see https://github.com/tomnomnom/meg#basic-usage)

**Comment by edoardottt** [comment]
Added in branch https://github.com/edoardottt/cariddi/tree/store-resp

@ocervell if interested, could you test it when u have free time? What do you think about that? If you have some suggestion let me know :)

**Comment by jaikishantulswani** [comment]
@edoardottt thank you for the implement. Here while testing this I found that it got stuck even on supplying a single target like

```
 cariddi -plain -s -ot https://example.com 

 cariddi -plain -sr -s -ot https://example.com
```
 but on both it got stuck, one more thing if it have an argument to control redirect -redirect true  or something like that 

please correct on the usage in above commands.

**Comment by edoardottt** [comment]
@jaikishantulswani 

First of all you should test using the branch `store-resp`, since the main and the devel branches don't have the `-sr` support yet.

Then cariddi is taking input in pipe, so something like this:
```console
echo https://example.com | go run cmd/cariddi/main.go
```

**Comment by jaikishantulswani** [comment]
@edoardottt Yes ! its working good, can you provide sample regex file too to use regexes from the file.
Thank you.

**Comment by edoardottt** [comment]
@jaikishantulswani let me know if you see some strange behavior

**Comment by jaikishantulswani** [comment]
@edoardottt sure and thank you again.

**Comment by edoardottt** [comment]
pushed in `devel`
