### ISSUE TITLE
Consider making binary releases

### ISSUE THREAD

**Issue by ocervell** [edoardottt/cariddi#146]
In resource-constrained environments we sometimes cannot afford to install full-blown Go + build packages with it: good practice is to have pre-packaged binary releases for each platform like https://github.com/projectdiscovery/httpx/releases.

See https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04#step-4-building-executables-for-different-architectures for the process of creating binary releases.

You can include this in a GitHub action workflow, by leveraging something like the https://github.com/marketplace/actions/go-release-binaries action which automates the process.

**Comment by edoardottt** [comment]
Thanks @ocervell. This will be prioritized.
