### ISSUE TITLE
crawl only unique urls

### ISSUE THREAD

**Issue by tilakpatel22** [edoardottt/cariddi#162]
Currently, when using Cariddi it is crawling lot of links again and again I think you should add an feature to crawl only new and unique webpages that will be really help users using Cariddi similar to hakrawler they have unique URL crawling feature

**Comment by edoardottt** [comment]
Hi! 
Can you provide please a test input? 
As far as I'm aware the option for disabling URL revisiting is disabled

**Comment by tilakpatel22** [comment]
[urls.txt](https://github.com/user-attachments/files/16899018/urls.txt) cat urls.txt | cariddi -s
check this file it is crawling single webpage multiple times

**Comment by edoardottt** [comment]
Just tried, there isn't any duplicate.

```bash
echo "https://igod.gov.in/" | cariddi -ot test
```

```bash
cat output-cariddi/test.results.txt | wc -l
1269
```

```bash
cat output-cariddi/test.results.txt | sort -u | wc -l
1269
```

**Comment by bafmaamy** [comment]
Hi, I`m facing the same issue, the number of urls are: 
```
cat alljsKatana3.txt | wc -l
763
```

but running cariddi lead to infinity rotating or something testing probably many more times:
`cat alljsKatana3.txt | cariddi -s -e -info -debug -intensive -rua -ot carridi-3.txt  | nl -w1 -s' '`

```
 | (_| (_| | |  | | (_| | (_| | |
  \___\__,_|_|  |_|\__,_|\__,_|_| v1.3.5

 > github.com/edoardottt/cariddi
 > edoardoottavianelli.it
========================================
1 https://api.example.com/assets/js/minut-logo.js
2 https://api.example.com/assets/js/utils.js
3 https://web.example.com/assets/account-a0f8b42b.js
4 https://web.example.com/assets/addbutton-fe9b96a7.js
5 https://web.example.com/assets/addmemberaccess-2
.....
962 https://web.example.com/assets/index.prod-b7001dcf.js
963 https://web.example.com/assets/Sandbox-1f8107bb.js
964 https://web.example.com/assets/ReferralProgram-d6b41742.js
965 https://web.example.com/assets/ParadiseHomeDetails-d254b92d.js
966 https://web.example.com/assets/HomeGroupsDropdown-1a374883.js
967 https://web.example.com/assets/IncidentReportDialogContainer-c6335b08.js
968 https://web.minut.com/assets/SettingTimeRange-254abaf4.js
^C
```
