### ISSUE TITLE
Error in installation from source after fork

### ISSUE THREAD

**Issue by devplayer55221** [edoardottt/cariddi#166]
**To Reproduce**
1. Fork the project
2. Clone the project made in personal profile
3. cd cariddi
4. go get ./...

**Observed behavior**
![image](https://github.com/user-attachments/assets/a3ae2fe1-91ba-40c6-810a-53cb9ab36cf4)

 - OS: Ubuntu 20.04

**Comment by edoardottt** [comment]
which golang version are you using?

**Comment by devplayer55221** [comment]
go version go1.13.8 linux/amd64

**Comment by edoardottt** [comment]
try with go1.18

**Comment by devplayer55221** [comment]
Yes, it worked

**Comment by devplayer55221** [comment]
Should I add it to the README file?

**Comment by edoardottt** [comment]
yes thanks!! 
after you need go you can insert `(>=1.18)`
