### ISSUE TITLE
Cariddi use request and response txt file as input

### ISSUE THREAD

**Issue by fngoo** [edoardottt/cariddi#2]
Cariddi could use burp or any proxy output as input

**Comment by fngoo** [comment]
My apologies, It's my mistake, my description is unclear.
Those txt file is not about requests to send, they are literally input, totally in localhost without network transfer.

For example, 
user paste response from BurpSuite then save it as **cariddi.input**, and **cariddi.input** may has juicy endpoint, secrets, etc.
User deliver **cariddi.input** to cariddi using pipe command and so on.

In short, it's a non-network and locally text option, what do you think?

**Comment by edoardottt** [comment]
Oh okay, now I've got it!
Yeah, It can be soooo useful.
I have to think on some things:
1. How can we collect input files (http responses) from Burpsuite? Copy and Paste? Or there is some extensions to dump all the responses?
2. How many input files we can collect and how? Is it useful to use cariddi on just one response? Maybe it would be better to collect thousands of them and then analyze them all together.

I have to figure out how we can solve the problems and then how to implement this :)
Good idea man!
I will leave the issue open for now and when I will have some updates I will post them here.
P.s. (Let's say also that now I'm on exams session, so I have also to study to pass exams, ahah let's see)

**Comment by fngoo** [comment]
ProjectDiscovery has high quality open-sourced tool for HTTP requests & responses collection.
https://github.com/projectdiscovery/proxify

Dump all the traffic into separate files in **logs** directory with request followed by the response using one command:
```
proxify -output logs
```

BurpSuite has export functionality, so that user could dump all the HTTP traffic.
Using Proxify, user could combine cariddi with any tool that has proxy function to dump traffic.
The final step is lead those file into Cariddi.

Wish you success in the exam!

**Comment by edoardottt** [comment]
Closing this issue because this can be achieved easily with gf from tomnomnom (https://github.com/tomnomnom/gf)
