### ISSUE TITLE
Add https://github.com/aels/subdirectories-discover as a wordlist

### ISSUE THREAD

**Issue by aels** [edoardottt/cariddi#33]
**Is your feature request related to a problem? Please describe.**
Ways to enrich crawler results.
**Describe the solution you'd like**
Add more lists to the brute force stage.
Taken from there https://github.com/aels/subdirectories-discover for example (yes, I'm the curator of this list)

**Comment by edoardottt** [comment]
Hi @aels! My pleasure. I don't think a wordlist will be useful in cariddi, since crawling doesnt need a wordlist.

I will take a look at it for scilla in the case. Thank you :)
