### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sasholy** [edoardottt/cariddi#56]
# internal/unsafeheader
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/cpu
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/abi

how to fix it

thx.

**Comment by edoardottt** [comment]
Hi! 
Sorry, I'm not understanding your problem, can you provide me a stack trace (error lines you see )? 

Enclose those lines in three backticks
\`\`\` 
write here
\`\`\`

**Comment by sasholy** [comment]
I cant install
┌──(kali㉿kali)-[~]
└─$ git clone https://github.com/edoardottt/cariddi.git; cd cariddi; go get; make linux
fatal: destination path 'cariddi' already exists and is not an empty directory.
# internal/unsafeheader
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/goexperiment
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# runtime/internal/sys
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/abi
etc.

sistem kali linux

**Comment by edoardottt** [comment]
Basically it's telling you that the cariddi folder already exists. Try (inside cariddi folder) `make unlinux`, then `make linux`

**Comment by sasholy** [comment]
┌──(kali㉿kali)-[~/cariddi]
└─$ make unlinux
[sudo] password for kali: 
Done.
                                                                                          
┌──(kali㉿kali)-[~/cariddi]
└─$ make linux
# internal/goexperiment
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/unsafeheader
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# runtime/internal/sys
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# runtime/internal/atomic
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/abi
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/race
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# sync/atomic
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/cpu
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# unicode/utf8
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# math/bits
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# unicode
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/itoa
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# unicode/utf16
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# crypto/subtle
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# crypto/internal/subtle
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# container/list
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# encoding
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# internal/nettrace
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# github.com/edoardottt/cariddi/scanner
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# golang.org/x/net/html/atom
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# golang.org/x/text/internal/utf8internal
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# github.com/gobwas/glob/util/runes
compile: version "go1.17.6" does not match go tool version "go1.18.2"
# golang.org/x/text/encoding/internal/identifier
compile: version "go1.17.6" does not match go tool version "go1.18.2"
make: *** [Makefile:25: linux] Error 2

**Comment by edoardottt** [comment]
I think that your problem is not with cariddi, but with golang itself.

It looks like you have problems with Go installation, try to see if you have correct values for `GOROOT` and `GOPATH` environment variables or try to re install go
