### ISSUE TITLE
Enhancement of Sorting URLs like URO

### ISSUE THREAD

**Issue by zy9ard3** [edoardottt/cariddi#75]
Hi @edoardottt 

Hope you are doing well !!

**Cariddi** : An Awesome & Nice tool, I came through recently and using actively

> Effectively collecting/crawling endpoints, finding juicy things & more...

**Describe the solution you'd like**

> I would like to suggest an **Enhancement of Sorting URLs like [URO](https://pypi.org/project/uro/)** for enhanced output without large results with multiple duplicates/junks

**Describe alternatives you've considered**

> Currently using [URO](https://pypi.org/project/uro/) written in python

**Additional context**

> ![Example Output](https://user-images.githubusercontent.com/67743789/197385706-602b6213-7354-43bb-8fe7-4f5fbd681a98.png)

*Kindly please let me know if anything I missed out, I'm glad to assist with pleasure on any questions/infos if required further*

Thanks & Regards,
@zy9ard3

**Comment by edoardottt** [comment]
Hi @zy9ard3 ! Thanks for the suggestion.

I don't think this is a good feature, cariddi imo should always output all the findings.

If you want to have a "nicer" output you can pipe cariddi with uro (`cariddi ... | uro`)
