### ISSUE TITLE
"domain formatted in a bad way" kills scan and debug doesn't give any info on the URL that caused this

### ISSUE THREAD

**Issue by cyb3rjerry** [edoardottt/cariddi#78]
**Describe the bug**
Hey there, so after running the scanner on an endpoint, I noticed that out of the blue I get a `domain formatted in a bad way` error. However, even when enabling -debug, I get no additional info as to what URL has killed the scan. Is this intended?

**To Reproduce**
1. Run `echo "https://xxxxxx.com" | cariddi -s -sf regex.txt  -intensive -ot results.txt`
2. Wait
3. Observe `domain formatted in a bad way` error

**Expected behavior**
Would it not be better to simply skip that URL rather than killing the scan via `os.Exit(1)`? 

**Screenshots**
![image](https://user-images.githubusercontent.com/92945113/201751692-b42ea604-b5b4-43d4-8cbb-4a4a36f94be1.png)

**Desktop (please complete the following information):**
 - OS: Linux XXXXXXXX 5.19.0-23-generic 24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
 - Version: Cariddi v1.1.9

**Additional context**

Let me know if you'd appreciate a hand in any way!

**Comment by cyb3rjerry** [comment]
Quick addendum, I also experience this with https://www.lg.com/ for example.
The command was: `echo "https://lg.com/" | cariddi -s -sf regex.txt -intensive`

**Comment by cyb3rjerry** [comment]
@edoardottt It sure looks good on my hand! Thanks a lot for the quick fix :)

Cheers!

**Comment by edoardottt** [comment]
Thanks to you :)
