### ISSUE TITLE
Initial call to robots.txt and sitemap.xml don't enforce ignored words

### ISSUE THREAD

**Issue by cyb3rjerry** [edoardottt/cariddi#81]
After review the code I've noticed that these two files don't follow the enforced ignored list that's passed via `-i`

@edoardottt Since it's only two calls at the very beginning do you feel like we should enfored the check or we should leave it as is? As the creator I feel like you would have the best insight on what behavior should/should not be enforced :) 

https://github.com/edoardottt/cariddi/blob/f52de6c99d7689876aff55662d70f216407be6c4/pkg/crawler/colly.go#L263-L286

**Comment by edoardottt** [comment]
Closed by [Fix Initial call - ignore ](https://github.com/edoardottt/cariddi/commit/d9d74ed498135cec88fa467b44cba8ac06bc8e01)
