### ISSUE TITLE
Second ctrl+c should force quit the program

### ISSUE THREAD

**Issue by cyb3rjerry** [edoardottt/cariddi#89]
**Describe the bug**
CTRL+C once initiates the "smooth" exit correctly. However, pressing it a second time should "force quit" as it currently simply hangs

**To Reproduce**
1. Run any long scan
2. Press CTRL+C twice
3. See error

**Expected behavior**
Force quit on second CTRL+C

**Screenshots**
![image](https://user-images.githubusercontent.com/92945113/201962462-21c6282e-da77-4529-ae6b-4fc8020c7f7a.png)

**Desktop (please complete the following information):**
Linux cyb3rjerry 5.19.0-23-generic 24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cyb3rjerry** [comment]
Crawling google with the intensive flag for example causes this issue and fills the ram pretty quickly
![image](https://user-images.githubusercontent.com/92945113/201963744-6329301e-20db-4b23-8235-2dd71a5746c8.png)

**Comment by cyb3rjerry** [comment]
Crawling google and trying to leave for example causes this
![image](https://user-images.githubusercontent.com/92945113/201963919-cfbe409d-65fb-47fd-ad7d-769255ffab95.png)

**Comment by edoardottt** [comment]
Can you confirm this https://github.com/edoardottt/cariddi/commit/c5471287980cdf22cd0872f914f95e2bcd094969 is fixing this issue? @cyb3rjerry

**Comment by cyb3rjerry** [comment]
@edoardottt LGTM however we might also want to halt printing URLs to avoid confusion
Either that or add a sleep before printing the exit message to make sure it gets printed at the bottom
![image](https://user-images.githubusercontent.com/92945113/201968596-3877f010-7dda-4ba9-8d13-4afd1daf03f4.png)

**Comment by edoardottt** [comment]
Those are the responses to the requests that have been made before pressing CTRL+C and still didn't get a response. Then when they get it, they print them. What about adding `os.Stdout = nil`? I don't know what could be a working solution..
